var path = require('path');

var webpack = require('webpack');
var TimestampWebpackPlugin = require('timestamp-webpack-plugin');

// npm install webpack timestamp-webpack-plugin jquery 


module.exports = {
    context: path.resolve('js'),
    entry: './app.js',
    output: {
        path: path.resolve('build/bundle/'),
        publicPath: path.resolve('/public/assets/'),
        filename: 'bundle.js'
    },

    devServer: {
        contentBase: 'public'
    },

    plugins: [
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery',
            'window.jQuery': 'jquery'
        }),

        new TimestampWebpackPlugin({
            path: __dirname,
            filename: 'timestamp.json'
        }),

        new webpack.BannerPlugin('*****\nGenerated by Webpack\n*******')

    ],
    resolve: {
        extensions: ['', '.js', '.es6']
    }
};